AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws-lambda-python-convuser-runtime

Parameters:
  VpcSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Lambdaを配置するサブネットID（複数可）
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPCのID（エンドポイント/SG作成に使用）
  RouteTableIds:
    Type: CommaDelimitedList
    Description: S3 Gatewayエンドポイントを関連付けるルートテーブルID（複数可、カンマ区切り）
  CreateS3GatewayEndpoint:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
    Description: S3 Gateway VPC Endpoint を作成するかどうか（既存の場合は false）
  S3GatewayEndpointId:
    Type: String
    Default: ""
    Description: 既存の S3 Gateway VPC Endpoint ID (vpce-xxxxx)。CreateS3GatewayEndpoint が false の場合に使用。
  CreateSsmInterfaceEndpoint:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
      - "false2"
    Description: SSM Interface VPC Endpoint を作成するかどうか（既存の場合は false）
  SsmVpcEndpointId:
    Type: String
    Default: ""
    Description: 既存の SSM VPC Endpoint ID (vpce-xxxxx)。CreateSsmInterfaceEndpoint が false の場合に使用。
  BucketName:
    Type: String
    Default: ""
    Description: ログ保存先のS3バケット名
  LambdaSecurityGroup:
    Type: String
    Default: ""
    Description: Lambda関数にアタッチするセキュリティグループ
  VpceSecurityGroup:
    Type: String
    Default: ""
    Description: VPCエンドポイントにアタッチするセキュリティグループ
  LambdaLogonLogoffRoleArn:
    Type: String
    Default: ""
    Description: Lambda関数に使用するIAMロールのARN


Conditions:
  CreateS3GatewayEndpointCondition: !Equals [ !Ref CreateS3GatewayEndpoint, "true" ]
  CreateSsmInterfaceEndpointCondition: !Equals [ !Ref CreateSsmInterfaceEndpoint, "true" ]

Resources:
  ##########################################################################
  # Lambda関数
  ##########################################################################
  ReciveLognLogoffFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: recieve_logonlogoff
      PackageType: Zip
      Handler: recieve_logonlogoff.recieve_logonlogoff
      Runtime: python3.13
      Environment:
        Variables:
          bucket_name: !Ref BucketName
      CodeUri: ./
      Timeout: 900
      MemorySize: 512
      Role: !Ref LambdaLogonLogoffRoleArn
      Architectures:
        - arm64
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds:
          - !Ref LambdaSecurityGroup

  ##########################################################################
  # VPC エンドポイント（S3: Gateway、SSM: Interface）
  ##########################################################################
  S3GatewayEndpointResource:
    Type: AWS::EC2::VPCEndpoint
    Condition: CreateS3GatewayEndpointCondition
    Properties:
      VpcEndpointType: Gateway
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds: !Ref RouteTableIds

  SsmInterfaceEndpointResource:
    Type: AWS::EC2::VPCEndpoint
    Condition: CreateSsmInterfaceEndpointCondition
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref VpcId
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      SubnetIds: !Ref VpcSubnetIds
      SecurityGroupIds:
        - !Ref VpceSecurityGroup
      PrivateDnsEnabled: true

Outputs:
  LambdaFunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt ReciveLognLogoffFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}:LambdaArn"
  LambdaSecurityGroupId:
    Description: Lambda Security Group ID
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}:LambdaSG"
  S3VpcEndpointId:
    Description: S3 Gateway VPC Endpoint ID (created or existing)
    Value: !If
      - CreateS3GatewayEndpointCondition
      - !Ref S3GatewayEndpointResource
      - !Ref S3GatewayEndpointId
  SsmVpcEndpointId:
    Description: SSM Interface VPC Endpoint ID (created or existing)
    Value: !If
      - CreateSsmInterfaceEndpointCondition
      - !Ref SsmInterfaceEndpointResource
      - !Ref SsmVpcEndpointId

